name: cargo install
author: David Tolnay
description: Fast `cargo install` action using a GitHub-based binary cache
inputs:
  crate:
    description: Name of crate as published to crates.io
    required: true
    default: cargo-outdated
  bin:
    description: Name of binary; default = same as crate name
    required: false
runs:
  using: composite
  steps:
    - name: Set some local variables
      id: vars
      shell: bash
      run: |
        echo "repository=https://github.com/swlynch99/install" >> $GITHUB_OUTPUT
        echo "key-id=830334D6A6010C41"                         >> $GITHUB_OUTPUT
        echo "binary=${{inputs.bin || inputs.crate}}"          >> $GITHUB_OUTPUT

    - name: Determine cargo bin directory
      run: echo "dir=$(dirname $(which cargo))" >> $GITHUB_OUTPUT
      shell: bash
      id: cargo

    - name: Download ${{steps.vars.outputs.binary}}
      shell: bash
      run: |
        curl --output ${{steps.cargo.outputs.dir}}/${{steps.vars.outputs.binary}} \
          ${{steps.vars.outputs.repository}}/releases/download/${{inputs.crate}}/${{steps.vars.outputs.binary}} \
          --location \
          --silent \
          --show-error \
          --fail \
          --retry 5

    - name: Download ${{steps.vars.outputs.binary}}.sig
      shell: bash
      run: |
        curl --output ${{runner.temp}}/${{steps.vars.outputs.binary}}.sig \
          ${{steps.vars.outputs.repository}}/releases/download/${{inputs.crate}}/${{steps.vars.outputs.binary}}.sig \
          --location \
          --silent \
          --show-error \
          --fail \
          --retry 5
    
    - name: Retrieve public key of signing key
      shell: bash
      run: gpg --output ${{runner.temp}}/signing-key.gpg --yes --dearmor ${{github.action_path}}/signing-key.asc
      
    - name: Verify gpg signature
      shell: bash
      run: |
        gpg \
          --no-default-keyring \
          --keyring ${{runner.temp}}/signing-key.gpg \
          --trusted-key ${{steps.vars.outputs.key-id}} \
          --verify ${{runner.temp}}/${{steps.vars.outputs.binary}}.sig \
          ${{steps.cargo.outputs.dir}}/${{steps.vars.outputs.binary}}
      
    - name: Set executable bit
      shell: bash
      run: |
        chmod +x ${{steps.cargo.outputs.dir}}/${{steps.vars.outputs.binary}}
