name: cargo-sweep

on:
  push:
    branches:
      - cargo-sweep
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      crate: cargo-sweep
    permissions:
      contents: write
    secrets: inherit
