name: cargo-audit

on:
  push:
    branches:
      - cargo-audit
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      crate: cargo-audit
    permissions:
      contents: write
    secrets: inherit
