name: cargo-deb

on:
  push:
    branches:
      - cargo-deb
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      crate: cargo-deb
    permissions:
      contents: write
    secrets: inherit
