name: cargo-sqlx

on:
  push:
    branches:
      - sqlx-cli
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      crate: sqlx-cli
      bin: cargo-sqlx
    permissions:
      contents: write
    secrets: inherit
