name: hurl

on:
  push:
    branches:
      - hurl
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      crate: hurl
    permissions:
      contents: write
    secrets: inherit
